### ISSUE TITLE
Cannot Create a New Presentation

### ISSUE THREAD

**Issue by jkdele** [Philip-Scott/Spice-up#109] opened 2017-05-17 17:36 UTC
I just installed Spice-Up through the eOS AppCentre and I cannot seem to create a new presentation. Regardless of whether I press "New Presentation" or "Open File", Spice-Up simply opens a file dialog.

**Comment by Philip-Scott** [comment] 2017-05-17 17:51
Sorry it's not that intuitive atm.... When you press New Presentation, that's asking where you want to save it, and with what name 

But i'm working on it, along with my workplace's UX Team to come up with a good workflow! :) 
Here's the project: https://github.com/Philip-Scott/Spice-up/projects/1

(I'm going to close it since it's really a duplicate of #17)

**Closed by Philip-Scott** 2017-05-17 17:51 UTC

**Comment by jkdele** [comment] 2017-05-17 18:08
There must be an issue with my installation in that case, because I can't seem to save the file to begin editing it. I can only create folders through the file dialog. Unless I'm simply too stupid to understand how to save the file even then.

**Comment by Philip-Scott** [comment] 2017-05-17 20:52
No problem :) If you first click on create a new one, then type the name of the file, you should be able to just save it by pressing enter. Does the save dialog close without showing anything?

**Comment by jkdele** [comment] 2017-05-18 03:53
When I enter a filename and press enter the path simply disappears. The dialog remains open and I have to terminate the whole application.

**Comment by Philip-Scott** [comment] 2017-05-18 05:15
You are typing the file name on the bottom, right? :smile: 

![screenshot from 2017-05-18 00 13 30](https://cloud.githubusercontent.com/assets/10786508/26187493/4753cf78-3b4e-11e7-8c7a-c6e6103aebd7.png)

**Comment by jkdele** [comment] 2017-05-18 12:40
I have no bottom bar at all, as I was suspecting. It doesn't become visible by expanding the dialog either. I assume it's an issue with elementary or just my install rather than your program.

Looks promising otherwise!

**Comment by Philip-Scott** [comment] 2017-05-18 15:30
Very weird, can you post a screenshot of the dialog you're getting, as well as running spice-up from the terminal and giving me the output? :) 

And could you also get a screenshot of the save-as dialog on Scratch? You can open it by one of the Headerbar buttons on the top left of the screen

**Comment by jkdele** [comment] 2017-05-18 15:48
Yeah, apparently the save dialog is broken in Scratch as well. I know for a fact that it was working fine before the eOS update, though. Can't even upload my screenshot because my browsers use the same dialog.

Sorry for bothering you about this when it seems the issue is just at my end.

**Comment by Philip-Scott** [comment] 2017-05-18 15:50
No, no problem :) It's interesting. You can upload your screenshot by drag and dropping into the comment box.

**Comment by jkdele** [comment] 2017-05-18 15:53
Here you go. I managed to fix it now with the help of [this](https://elementaryos.stackexchange.com/questions/1638/buttons-are-missing-in-the-file-chooser-dialog-what-should-i-do). Apparently it was nothing more than messed up GTK settings.

![spiceup](https://cloud.githubusercontent.com/assets/8886074/26211429/055a251a-3bfb-11e7-9230-a14bf02cce05.jpg)
