### ISSUE TITLE
Default open file dialog does not list ".spice" files

### ISSUE THREAD

**Issue by rugk** [Philip-Scott/Spice-up#177] opened 2017-12-09 10:53 UTC
The default file dialog does not list the ".spice" files. I have to select "All files" instead of "Presentations" (at the bottom right) in order to be able to select the correct file.

installed from Flathub
GNOME v3.26
Fedora 27

**Comment by Philip-Scott** [comment] 2017-12-09 20:26
as with #178, the flathub is not registering the mime of spice-up.

You should files those issues here :) https://github.com/flathub/com.github.philip_scott.spice-up

Marking this as a duplicate of #178

**Closed by Philip-Scott** 2017-12-09 20:26 UTC

**Comment by rugk** [comment] 2017-12-09 22:45
Done: https://github.com/flathub/com.github.philip_scott.spice-up/issues/3
